stages: # ステージの定義
  - build
  - test
  - deploy

before_script:
  - echo "$GCP_KEY" > ${CI_PROJECT_DIR}/gcp-key.json
  - gcloud auth activate-service-account --key-file=gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud container clusters get-credentials study --zone asia-northeast1-a
  - mkdir -p ~/.kube
  - cp "$KUBECONFIG_DATA" ~/.kube/config
  - export KUBECONFIG=~/.kube/config


build_job: # ジョブ名
  stage: build # ステージ名
  script:
    - kubectl apply -f k8s/

test_1:
  stage: test
  script:
    - echo "test1"
test_2:
  stage: test
  script:
    - echo "test2"

deploy_job: # ジョブ名
  stage: deploy # ステージ名
  script:
    - echo "Deploying the project..."
  only: # 条件付き実行
    - main # main ブランチのみで実行

default:
  image: $DEFAULT_CI_IMAGE
  timeout: 90m


variables:
  DEFAULT_CI_IMAGE: "mcp/kubernetes"
