
stages:
  - test
  - build
  - deploy

variables:
  KUBECONFIG: "$CI_PROJECT_DIR/kubeconfig"  # ファイルとして展開

before_script:
  - echo "$KUBECONFIG_DATA" > $KUBECONFIG
  - chmod 600 $KUBECONFIG
  - export KUBECONFIG=$KUBECONFIG
  - kubectl config get-contexts
test-helm:
  image: lachlanevenson/k8s-helm:latest
  script:
    - helm version

build-image:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  before_script: []
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
deploy:
  image: lachlanevenson/k8s-helm:latest
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  variables:
    KUBECONFIG: "$CI_PROJECT_DIR/kubeconfig"
  before_script:
    - echo "$KUBECONFIG_DATA" > $KUBECONFIG
    - chmod 600 $KUBECONFIG  # 推奨：kubeconfigの読み取り制限
    - export KUBECONFIG=$KUBECONFIG
    - kubectl config get-contexts
  script:
    - kubectl apply -f k8s/
